BENCHMARKS_ROOT_PATH = "/media/ftrujillo/FRD/Projects/UIUC/DLH/CS598_Final/mimic3-benchmarks"
MIMIC_UNPROCESSED_DATA_PATH = "/media/ftrujillo/FRD/Projects/UIUC/DLH/CS598_Final/data/mimic3"
NOTE_EXTRACTION_OUT_PATH = f"{BENCHMARKS_ROOT_PATH}/data/root/text_fixed"
MULTI_MODAL_MIMIC_PATH = "/media/ftrujillo/FRD/Projects/UIUC/DLH/CS598_Final/MultimodalMIMIC"
PROJECT_BASE_PATH = "/media/ftrujillo/FRD/Projects/UIUC/DLH/CS598_Final/"
